### ISSUE TITLE
仮想デスクトップ使用時に、RunningApps Switchのウインドウが表示されない

### ISSUE THREAD

**Issue by nekowasabi** [u338steven/UIAssistant#1]
■環境
Windows10 64bit build10586.318
仮想デスクトップソフトdexpot（http://www.forest.impress.co.jp/docs/review/20100420_362480.html）を使用

■現象
移動元仮想デスクトップ（デスクトップAとする）から移動先仮想デスクトップ（デスクトップＢとする）に移動後、
RunningApps Switchを実行すると、タスク切り替えウインドウが表示されない。
デスクトップＡに戻ってRunningApps Switchを実行するとウインドウが表示される。

調査した結果、UIAssistant.exeを実行した仮想デスクトップでのみ、ウインドウが表示されます。
上記の現象は、Hit a hint for windows使用時は発生いたしませんでした。

**Comment by u338steven** [comment]
ご報告ありがとうございます。
修正して ver.0.2.3.1 として公開しました。
[Download](https://github.com/u338steven/UIAssistant/releases)

修正後に稼動確認したところ、仮想デスクトップ切り替え直後すぐに UIAssistant をホットキー駆動させると、
同様にウィンドウが消えてしまう場合がありました。
これは dexpot のウィンドウを隠す処理のタイミングと重なってしまうため発生します。
ざっくりと以下のような処理の流れになり、ウィンドウが失踪します。

1. dexpot で仮想デスクトップ切り替え 
  1. 移動前のデスクトップにあるウィンドウを隠す処理
  1. 移動後のデスクトップにあるウィンドウを表示する処理
2. UIAssistant をホットキーでウィンドウ表示
3. dexpot のウィンドウを隠す処理が継続していた場合、UIAssistant も隠されてしまう

これに関しましては UIAssistant 側では対処しようがないので、ご注意ください。
失踪してしまった場合、一旦キャンセル(デフォルトだと Escape キー)して、
再度ホットキー押下でウィンドウは表示されるようになる…はずです。

**Comment by nekowasabi** [comment]
修正ありがとうございます。
動作を確認しましたところ、意図した通りの動作となりました。

また、Windows10 InsiderPreview版で最新バージョンを実行する際、
たまにタスクトレイにUIAssistantのアイコンが表示されず（プロセスには存在する）、
動作しないことがありました。
こちらは特殊な環境下での現象となりますので、一応の報告となります。

**Comment by u338steven** [comment]
確認ありがとうございました。本件はクローズします。

> また、Windows10 InsiderPreview版で最新バージョンを実行する際、
> たまにタスクトレイにUIAssistantのアイコンが表示されず（プロセスには存在する）、
> 動作しないことがありました。

ご報告ありがとうございます。
Insider Preview 版は、トレイアイコンが表示されない問題が直ったり再発したりと安定していないようです。
↓ ちょっと古い内容ですが。

> It doesn't show on the latest Windows 10 insider build, but the taskbar has serious issues with this windows build, hope to see it fixed soon.

> With build 14316 the taskbar icon is back!

https://forums.plex.tv/discussion/209276/plex-system-tray-icon-missing

> We fixed an issue where the taskbar's overflow tray for notification area (systray) icons was not being padded correctly for certain multi-monitor setups.

https://blogs.windows.com/windowsexperience/2016/04/26/announcing-windows-10-insider-preview-build-14332/

ですので、こちらの件は Windows の次の正式リリース(Anniversary Update)まで様子見させてください。
